package com.sep.util;

public enum EventType {
    PLACEHOLDER_REQUEST,
    REGISTER_REQUEST,
    LOGIN_REQUEST,

    BRANCHES_GET_REQUEST,
    BRANCH_GET_REQUEST,
    BRANCH_CREATE_REQUEST,
    BRANCH_REMOVE_REQUEST,

    FOOD_GET_REQUEST,
    FOOD_ADD_REQUEST
}
